export const mockData = [
    {
        "stockCode": "ACV",
        "name": "Tổng Công ty Cảng Hàng không Việt Nam - CTCP",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-1.2",
        "changePc": "-1.06",
        "changePriceValue": -1.2,
        "changePercentValue": -1.06,
        "lastPrice": 112,
        "r": 113.2,
        "f": 96.3,
        "c": 130.1,
        "volume": 217700,
        "marketCapital": 247519264573200
    },
    {
        "stockCode": "VGI",
        "name": "Tổng Công ty cổ phần Đầu tư Quốc tế Viettel",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-1.1",
        "changePc": "-1.58",
        "changePriceValue": -1.1,
        "changePercentValue": -1.58,
        "lastPrice": 68.4,
        "r": 69.5,
        "f": 59.1,
        "c": 79.9,
        "volume": 1179100,
        "marketCapital": 210936116160000
    },
    {
        "stockCode": "MCH",
        "name": "CTCP Hàng tiêu dùng Masan",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "+0.5",
        "changePc": "+0.24",
        "changePriceValue": 0.5,
        "changePercentValue": 0.24,
        "lastPrice": 210,
        "r": 209.5,
        "f": 178.1,
        "c": 240.9,
        "volume": 19700,
        "marketCapital": 149384989879200
    },
    {
        "stockCode": "BSR",
        "name": "CTCP Lọc hóa Dầu Bình Sơn",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.2",
        "changePc": "-0.83",
        "changePriceValue": -0.2,
        "changePercentValue": -0.83,
        "lastPrice": 24,
        "r": 24.2,
        "f": 20.6,
        "c": 27.8,
        "volume": 7061900,
        "marketCapital": 75342140668800
    },
    {
        "stockCode": "VEA",
        "name": "Tổng Công ty Máy động lực và Máy nông nghiệp Việt Nam – CTCP",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.1",
        "changePc": "-0.22",
        "changePriceValue": -0.1,
        "changePercentValue": -0.22,
        "lastPrice": 44.7,
        "r": 44.8,
        "f": 38.1,
        "c": 51.5,
        "volume": 469000,
        "marketCapital": 59928880000000
    },
    {
        "stockCode": "MVN",
        "name": "Tổng Công ty Hàng hải Việt Nam - CTCP",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.3",
        "changePc": "-0.75",
        "changePriceValue": -0.3,
        "changePercentValue": -0.75,
        "lastPrice": 39.5,
        "r": 39.8,
        "f": 33.9,
        "c": 45.7,
        "volume": 11400,
        "marketCapital": 48023520000000
    },
    {
        "stockCode": "FOX",
        "name": "CTCP Viễn thông FPT",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.3",
        "changePc": "-0.32",
        "changePriceValue": -0.3,
        "changePercentValue": -0.32,
        "lastPrice": 94,
        "r": 94.3,
        "f": 80.2,
        "c": 108.4,
        "volume": 137200,
        "marketCapital": 46246610499600
    },
    {
        "stockCode": "VEF",
        "name": "CTCP Trung tâm Hội chợ Triển lãm Việt Nam",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "+0.4",
        "changePc": "+0.17",
        "changePriceValue": 0.4,
        "changePercentValue": 0.17,
        "lastPrice": 229.9,
        "r": 229.5,
        "f": 195.1,
        "c": 263.9,
        "volume": 7200,
        "marketCapital": 38151640450000
    },
    {
        "stockCode": "SSH",
        "name": "CTCP Phát triển Sunshine Homes",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.3",
        "changePc": "-0.44",
        "changePriceValue": -0.3,
        "changePercentValue": -0.44,
        "lastPrice": 67.4,
        "r": 67.7,
        "f": 57.6,
        "c": 77.8,
        "volume": 55800,
        "marketCapital": 25350000000000
    },
    {
        "stockCode": "DNH",
        "name": "CTCP Thủy điện Đa Nhim - Hàm Thuận - Đa Mi",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "0.0",
        "changePc": "0.0",
        "changePriceValue": 0,
        "changePercentValue": 0,
        "lastPrice": 0,
        "r": 45.6,
        "f": 38.8,
        "c": 52.4,
        "volume": 0,
        "marketCapital": 19261440000000
    },
    {
        "stockCode": "QNS",
        "name": "CTCP Đường Quảng Ngãi",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "+0.1",
        "changePc": "+0.21",
        "changePriceValue": 0.1,
        "changePercentValue": 0.21,
        "lastPrice": 48.8,
        "r": 48.7,
        "f": 41.4,
        "c": 56,
        "volume": 175800,
        "marketCapital": 17418669804000
    },
    {
        "stockCode": "OIL",
        "name": "Tổng Công ty Dầu Việt Nam - CTCP",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.3",
        "changePc": "-1.91",
        "changePriceValue": -0.3,
        "changePercentValue": -1.91,
        "lastPrice": 15.4,
        "r": 15.7,
        "f": 13.4,
        "c": 18,
        "volume": 2717500,
        "marketCapital": 16237403150000
    },
    {
        "stockCode": "IDP",
        "name": "CTCP Sữa Quốc tế ",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "+10.0",
        "changePc": "+3.85",
        "changePriceValue": 10,
        "changePercentValue": 3.85,
        "lastPrice": 270,
        "r": 260,
        "f": 221,
        "c": 299,
        "volume": 1000,
        "marketCapital": 16069162720000
    },
    {
        "stockCode": "VSF",
        "name": "Tổng Công ty Lương thực Miền Nam - CTCP",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "0.0",
        "changePc": "0.0",
        "changePriceValue": 0,
        "changePercentValue": 0,
        "lastPrice": 32,
        "r": 32,
        "f": 27.2,
        "c": 36.8,
        "volume": 500,
        "marketCapital": 16000000000000
    },
    {
        "stockCode": "VNZ",
        "name": "CTCP VNG ",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "0.0",
        "changePc": "0.0",
        "changePriceValue": 0,
        "changePercentValue": 0,
        "lastPrice": 0,
        "r": 520.3,
        "f": 442.3,
        "c": 598.3,
        "volume": 0,
        "marketCapital": 14971456000000
    },
    {
        "stockCode": "MSR",
        "name": "CTCP Masan High-Tech Materials",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.3",
        "changePc": "-2.26",
        "changePriceValue": -0.3,
        "changePercentValue": -2.26,
        "lastPrice": 13,
        "r": 13.3,
        "f": 11.4,
        "c": 15.2,
        "volume": 342400,
        "marketCapital": 14728682628000
    },
    {
        "stockCode": "SNZ",
        "name": "Tổng Công ty cổ phần Phát triển Khu Công nghiệp",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "0.0",
        "changePc": "0.0",
        "changePriceValue": 0,
        "changePercentValue": 0,
        "lastPrice": 34.4,
        "r": 34.4,
        "f": 29.3,
        "c": 39.5,
        "volume": 5000,
        "marketCapital": 13064265460000
    },
    {
        "stockCode": "PHP",
        "name": "CTCP Cảng Hải Phòng",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-1.0",
        "changePc": "-3.41",
        "changePriceValue": -1,
        "changePercentValue": -3.41,
        "lastPrice": 28.3,
        "r": 29.3,
        "f": 25,
        "c": 33.6,
        "volume": 102200,
        "marketCapital": 9416448000000
    },
    {
        "stockCode": "MML",
        "name": "CTCP Masan MeatLife",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "+0.6",
        "changePc": "+2.23",
        "changePriceValue": 0.6,
        "changePercentValue": 2.23,
        "lastPrice": 27.5,
        "r": 26.9,
        "f": 22.9,
        "c": 30.9,
        "volume": 30100,
        "marketCapital": 8938509953100
    },
    {
        "stockCode": "ABB",
        "name": "Ngân hàng TMCP An Bình",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "0.0",
        "changePc": "0.0",
        "changePriceValue": 0,
        "changePercentValue": 0,
        "lastPrice": 7.8,
        "r": 7.8,
        "f": 6.7,
        "c": 8.9,
        "volume": 776100,
        "marketCapital": 8073286743600
    },
    {
        "stockCode": "VGT",
        "name": "Tập đoàn Dệt May Việt Nam",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.1",
        "changePc": "-0.65",
        "changePriceValue": -0.1,
        "changePercentValue": -0.65,
        "lastPrice": 15.3,
        "r": 15.4,
        "f": 13.1,
        "c": 17.7,
        "volume": 2066400,
        "marketCapital": 7700000000000
    },
    {
        "stockCode": "BGE",
        "name": "CTCP BCG Energy",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.1",
        "changePc": "-0.93",
        "changePriceValue": -0.1,
        "changePercentValue": -0.93,
        "lastPrice": 10.6,
        "r": 10.7,
        "f": 9.1,
        "c": 12.3,
        "volume": 61100,
        "marketCapital": 7665000000000
    },
    {
        "stockCode": "SBH",
        "name": "CTCP Thủy điện Sông Ba Hạ",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-2.1",
        "changePc": "-3.81",
        "changePriceValue": -2.1,
        "changePercentValue": -3.81,
        "lastPrice": 53,
        "r": 55.1,
        "f": 46.9,
        "c": 63.3,
        "volume": 700,
        "marketCapital": 7080825000000
    },
    {
        "stockCode": "PGB",
        "name": "Ngân hàng TMCP Thịnh vượng và Phát triển",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "+0.3",
        "changePc": "+1.85",
        "changePriceValue": 0.3,
        "changePercentValue": 1.85,
        "lastPrice": 16.5,
        "r": 16.2,
        "f": 13.8,
        "c": 18.6,
        "volume": 6100,
        "marketCapital": 6888000000000
    },
    {
        "stockCode": "MPC",
        "name": "CTCP Tập đoàn Thủy sản Minh Phú",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "0.0",
        "changePc": "0.0",
        "changePriceValue": 0,
        "changePercentValue": 0,
        "lastPrice": 16.9,
        "r": 16.9,
        "f": 14.4,
        "c": 19.4,
        "volume": 36900,
        "marketCapital": 6798084100000
    },
    {
        "stockCode": "HND",
        "name": "CTCP Nhiệt điện Hải Phòng",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "+0.1",
        "changePc": "+0.74",
        "changePriceValue": 0.1,
        "changePercentValue": 0.74,
        "lastPrice": 13.6,
        "r": 13.5,
        "f": 11.5,
        "c": 15.5,
        "volume": 16100,
        "marketCapital": 6750000000000
    },
    {
        "stockCode": "QTP",
        "name": "CTCP Nhiệt điện Quảng Ninh",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "0.0",
        "changePc": "0.0",
        "changePriceValue": 0,
        "changePercentValue": 0,
        "lastPrice": 14.9,
        "r": 14.9,
        "f": 12.7,
        "c": 17.1,
        "volume": 170100,
        "marketCapital": 6705000000000
    },
    {
        "stockCode": "TVN",
        "name": "Tổng Công ty Thép Việt Nam - CTCP",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "+0.1",
        "changePc": "+1.02",
        "changePriceValue": 0.1,
        "changePercentValue": 1.02,
        "lastPrice": 9.9,
        "r": 9.8,
        "f": 8.4,
        "c": 11.2,
        "volume": 1280100,
        "marketCapital": 6644400000000
    },
    {
        "stockCode": "DVN",
        "name": "Tổng Công ty Dược Việt Nam - CTCP",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "-0.7",
        "changePc": "-2.55",
        "changePriceValue": -0.7,
        "changePercentValue": -2.55,
        "lastPrice": 26.8,
        "r": 27.5,
        "f": 23.4,
        "c": 31.6,
        "volume": 206000,
        "marketCapital": 6493800000000
    },
    {
        "stockCode": "SJG",
        "name": "Tổng Công ty Sông Đà - CTCP",
        "stockExchange": "UPCOM",
        "stockType": "COMPANY",
        "changePrice": "0.0",
        "changePc": "0.0",
        "changePriceValue": 0,
        "changePercentValue": 0,
        "lastPrice": 14,
        "r": 14,
        "f": 11.9,
        "c": 16.1,
        "volume": 2300,
        "marketCapital": 6293519568000
    }
]